apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: proyecto_git
  annotations:
    github.com/project-slug: juligomez2008/proyecto_git
    venue/parametro1: 1234567890abcdefg
    venue/parametro2: 'esta es una prueba'
    venue/city: 'Bogota'
spec:
  type: other
  lifecycle: unknown
  owner: guests
