apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: proyecto_git
  annotations:
    github.com/project-slug: juligomez2008/proyecto_git
    pluginopex/parametro1: 1234567890abcdefg
    pluginopex/parametro2: 'esta es una prueba'
    pluginopex/city: 'Bogota'
    dev.bancolombia.com/appcode: nu0080001
spec:
  type: service
  lifecycle: unknown
  owner: guests
